
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listRepos() : Promise<Repo[]> {
    return await TAURI_INVOKE("list_repos");
},
async getRepo(id: string) : Promise<Repo> {
    return await TAURI_INVOKE("get_repo", { id });
},
async createRepo(input: CreateRepoInput) : Promise<Repo> {
    return await TAURI_INVOKE("create_repo", { input });
},
async updateRepo(input: UpdateRepoInput) : Promise<Repo> {
    return await TAURI_INVOKE("update_repo", { input });
},
async deleteRepo(id: string) : Promise<null> {
    return await TAURI_INVOKE("delete_repo", { id });
},
async listWorkspaces(repositoryId: string | null) : Promise<Workspace[]> {
    return await TAURI_INVOKE("list_workspaces", { repositoryId });
},
async getWorkspace(id: string) : Promise<Workspace> {
    return await TAURI_INVOKE("get_workspace", { id });
},
async createWorkspace(input: CreateWorkspaceInput) : Promise<Workspace> {
    return await TAURI_INVOKE("create_workspace", { input });
},
async archiveWorkspace(id: string) : Promise<Workspace> {
    return await TAURI_INVOKE("archive_workspace", { id });
},
async getSetting(key: string) : Promise<Setting> {
    return await TAURI_INVOKE("get_setting", { key });
},
async setSetting(key: string, value: string) : Promise<Setting> {
    return await TAURI_INVOKE("set_setting", { key, value });
},
async getAllSettings() : Promise<Setting[]> {
    return await TAURI_INVOKE("get_all_settings");
},
/**
 * Get pane info for all workspaces that have active tmux windows.
 * Used by the frontend for polling active sessions.
 */
async getActiveClaudeSessions() : Promise<WorkspacePaneInfo[]> {
    return await TAURI_INVOKE("get_active_claude_sessions");
},
/**
 * Open a Claude session in a workspace.
 * - If Claude is already running → attach to the existing window
 * - If no Claude running → create a new pane with claude, then attach
 */
async openClaudeSession(workspaceId: string) : Promise<string> {
    return await TAURI_INVOKE("open_claude_session", { workspaceId });
},
/**
 * Get session history for a workspace (from ~/.claude/projects/).
 */
async getWorkspaceSessions(workspaceId: string) : Promise<ClaudeSessionEntry[]> {
    return await TAURI_INVOKE("get_workspace_sessions", { workspaceId });
},
/**
 * Resume a specific Claude session by session_id.
 * Reuses an idle pane if available, otherwise creates a new one.
 */
async resumeClaudeSession(workspaceId: string, sessionId: string) : Promise<string> {
    return await TAURI_INVOKE("resume_claude_session", { workspaceId, sessionId });
},
/**
 * List panes for a specific workspace.
 */
async listWorkspacePanes(workspaceId: string) : Promise<TmuxPane[]> {
    return await TAURI_INVOKE("list_workspace_panes", { workspaceId });
},
/**
 * Open a shell pane in the workspace window.
 */
async openShellPane(workspaceId: string) : Promise<string> {
    return await TAURI_INVOKE("open_shell_pane", { workspaceId });
},
/**
 * Kill a specific pane in a workspace window.
 */
async killPane(workspaceId: string, paneIndex: number) : Promise<string> {
    return await TAURI_INVOKE("kill_pane", { workspaceId, paneIndex });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * A single session entry from ~/.claude/projects/<path>/sessions-index.json
 */
export type ClaudeSessionEntry = { session_id: string; first_prompt: string | null; message_count: number | null; created: string | null; modified: string | null; git_branch: string | null; is_sidechain: boolean | null }
export type CreateRepoInput = { name: string; remote_url: string; root_path: string; default_branch?: string; remote?: string; display_order?: number; conductor_config: JsonValue | null }
export type CreateWorkspaceInput = { repository_id: string; directory_name: string; branch: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Repo = { id: string; name: string; remote_url: string; default_branch: string; root_path: string; remote: string; display_order: number; conductor_config: JsonValue | null; created_at: string; updated_at: string }
export type Setting = { key: string; value: string; created_at: string; updated_at: string }
/**
 * A tmux pane within the Bunyan-managed tmux server.
 */
export type TmuxPane = { 
/**
 * Pane index within its window
 */
pane_index: number; 
/**
 * Current command running in the pane (e.g. "claude", "zsh")
 */
command: string; 
/**
 * Whether this is the currently selected pane in the window
 */
is_active: boolean; 
/**
 * Current working directory of the pane
 */
workspace_path: string }
export type UpdateRepoInput = { id: string; name: string | null; default_branch: string | null; display_order: number | null; conductor_config: JsonValue | null }
export type Workspace = { id: string; repository_id: string; directory_name: string; branch: string; state: WorkspaceState; created_at: string; updated_at: string }
/**
 * Info about all panes in a workspace's tmux window.
 */
export type WorkspacePaneInfo = { workspace_id: string; repo_name: string; workspace_name: string; panes: TmuxPane[] }
export type WorkspaceState = "ready" | "archived"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
